# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 32);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20151106123354");
user_pref("browser.shell.defaultBrowserCheckCount", 2);
user_pref("browser.slowStartup.averageTime", 3329);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20151106123354");
user_pref("browser.startup.homepage_override.mstone", "42.0");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:42.0");
user_pref("extensions.lastAppVersion", "42.0");
user_pref("extensions.lastPlatformVersion", "42.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/home/erkanmdr/Workscape/HELYX/MiDoRi-Prolockter/light/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"42.0\",\"st\":1451218836000,\"mt\":1446788859000}}}");
user_pref("network.cookie.prefsMigrated", true);
user_pref("permissions.default.image", 2);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("privacy.sanitize.migrateClearSavedPwdsOnExit", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1451225231);
